# Generated by Django 4.0.4 on 2022-05-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('Username', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default=0, max_length=3)),
                ('dob', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
